version: '3.6'

services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210713
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    ports:
      - 7900:7900
    links:
      - web:web
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}

  firefox:
    container_name: ddev-${DDEV_SITENAME}-firefox
    image: selenium/standalone-firefox:4.0.0-rc-1-prerelease-20210713
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    ports:
      - 7901:7900
    links:
      - web:web
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
